# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Diversity and Inclusion Efforts at Data Management Conference Venues
email: arunkk@eng.ucsd.edu
description: >- # this means to ignore newlines until "baseurl:"
  The Data Management community is committed to the promotion of diversity and inclusion in all aspects of our professional activities.
  We celebrate the diversity in our community and welcome everyone regardless of age, gender identity, race, ethnicity, socioeconomic background,
  country of origin, religion, sexual orientation, physical ability, education, and work experience. We also welcome people and opinions of all political persuasions,
  as long as they abide by the ACM policy against harassment. Our initiative coordinates D&I efforts across the data management community and includes this yearâ€™s D&I 
  hairs of SIGMOD, VLDB, SoCC, and ICDE.

baseurl:
url: https://dbdni.github.io

include:
  - .htaccess

sass:
  sass_dir: _sass
